services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=encanto_personalizados'
      - 'MYSQL_PASSWORD=encanteta'
      - 'MYSQL_ROOT_PASSWORD=encanteta'
      - 'MYSQL_USER=cynapseta'
    ports:
      - '3307:3306'

  whatsapp_api:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    command: ["rest"]
    restart: unless-stopped
    ports:
      - '3001:3000'
    env_file:
      - ./infra/whatsapp/.env
    volumes:
      - ./infra/whatsapp/storages:/app/storages
      - ./infra/whatsapp/statics:/app/statics
