name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        working-directory: EncantoPersonalizados
        run: docker build -t israelcoaquira/encanto-backend:latest .

      - name: Push Docker image
        run: |
          cd EncantoPersonalizados
          docker push israelcoaquira/encanto-backend:latest

      - name: Deploy backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_BASTION }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            ssh -A ubuntu@${{ secrets.PRIVATE_HOST }} << 'EOF'
              cd /opt/encanto
              sudo docker compose pull
              sudo docker compose down
              sudo docker compose up -d
            EOF
